export const ADD_1 = 'ADD_1'
export const SUB_1 = 'SUB_1'
export const ADD_NUMBER_1 = 'ADD_NUMBER_1'
export const ADD_2 = 'ADD_2'
export const SUB_2 = 'SUB_2'
export const ADD_NUMBER_2 = 'ADD_NUMBER_2'
